# Generated by Django 4.2.10 on 2024-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=254707371209, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
