# Generated by Django 4.2.10 on 2024-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
