name: Build and Test

on:
  push:
    branches: [main]

jobs:
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python manage.py test
